Cleanup
Signed-off-by: Tyler Auerbeck <tylerauerbeck@users.noreply.github.com>

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -1,30 +1,31 @@
 #!/bin/bash
 
-export HELM_EXPERIMENTAL_OCI=1
+FAIL_CHECK=0
 
-if [ -z "${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_CHART_PATH}" ]; then
-  export CHART_PATH="charts/${NAME}"
-else
-  export CHART_PATH="${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_CHART_PATH}"
-fi
+export HELM_EXPERIMENTAL_OCI=1
 
 if [ -z "${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY}" ]; then
   echo "REGISTRY is not set"
-  exit 1
+  FAIL_CHECK=1
 else
   export REGISTRY="${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY}"
 fi
 
 if [ -z "${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY_USERNAME}" ]; then
   echo "REGISTRY_USERNAME is not set"
-  exit 1
+  FAIL_CHECK=1
 else
   export REGISTRY_USERNAME="${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY_USERNAME}"
 fi
 
 if [ -z "${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY_PASSWORD}" ]; then
   echo "REGISTRY_PASSWORD is not set"
-  exit 1
+  FAIL_CHECK=1
 else
   export REGISTRY_PASSWORD="${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_REGISTRY_PASSWORD}"
+fi
+
+if [ ${FAIL_CHECK} -eq 1 ]; then
+  echo "Failed to set required environment variables. Check previous output for details."
+  exit 1
 fi
